# Machine Learning Algorithms

In [1]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

## Linear Regression

Linear Regression is a linear machine learning model that assumes a linear relationship between the input variables (x) and the single output variable (y). It uses this information to predict the value of y based on the value of x.

In [2]:
# Required packages
from sklearn.linear_model import LinearRegression #Linear regression package
from sklearn.model_selection import train_test_split

In [3]:
# Importing a dataset for linear regression
from sklearn.datasets import load_boston
boston = load_boston()
X = boston['data']
y = boston['target']
# Split the data into training and testing datasets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [4]:
# Syntax for creating a Linear Regression model

# LinearRegression(*, fit_intercept=True, copy_X=True, n_jobs=None, positive=False)

# fit_intercept - calculate the y-intercept of the model
# copy_X - Changes the value of x entered in the model
# positive - forces the coefficients to be positive

#Simple model
lr = LinearRegression()
lr.fit(X_train,y_train)
y_pred = lr.predict(X_test)

In [5]:
# Exploring the input & output

# Input: A two-dimensional array which contains all the features of the boston housing dataset
print("Input : ", X_test)

# Output: The ouput array is the prediction
print("Expected output : ", y_test)
print("Predicted output : ", y_pred)

Input :  [[6.72400e-02 0.00000e+00 3.24000e+00 ... 1.69000e+01 3.75210e+02
  7.34000e+00]
 [9.23230e+00 0.00000e+00 1.81000e+01 ... 2.02000e+01 3.66150e+02
  9.53000e+00]
 [1.14250e-01 0.00000e+00 1.38900e+01 ... 1.64000e+01 3.93740e+02
  1.05000e+01]
 ...
 [1.68118e+01 0.00000e+00 1.81000e+01 ... 2.02000e+01 3.96900e+02
  3.08100e+01]
 [4.92980e-01 0.00000e+00 9.90000e+00 ... 1.84000e+01 3.96900e+02
  4.54000e+00]
 [2.98500e-02 0.00000e+00 2.18000e+00 ... 1.87000e+01 3.94120e+02
  5.21000e+00]]
Expected output :  [22.6 50.  23.   8.3 21.2 19.9 20.6 18.7 16.1 18.6  8.8 17.2 14.9 10.5
 50.  29.  23.  33.3 29.4 21.  23.8 19.1 20.4 29.1 19.3 23.1 19.6 19.4
 38.7 18.7 14.6 20.  20.5 20.1 23.6 16.8  5.6 50.  14.5 13.3 23.9 20.
 19.8 13.8 16.5 21.6 20.3 17.  11.8 27.5 15.6 23.1 24.3 42.8 15.6 21.7
 17.1 17.2 15.  21.7 18.6 21.  33.1 31.5 20.1 29.8 15.2 15.  27.5 22.6
 20.  21.4 23.5 31.2 23.7  7.4 48.3 24.4 22.6 18.3 23.3 17.1 27.9 44.8
 50.  23.  21.4 10.2 23.3 23.2 18.9 13.4 21.9 24.8 11.9

In [6]:
# Calculating the Accuracy
# Accuracy of a linear model can't be calculated, the accuracy is predicted using error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

# Mean Squared Error
print("Mean Squared Error:",mean_squared_error(y_test, y_pred)) # tells you how close a regression line is to a set of points
# squaring is necessary to remove any negative signs

# Root Mean Squared Error
print("Root Mean Squared Error:", mean_squared_error(y_test, y_pred, squared=False))

# R2 Score
print("R^2 Score:", r2_score(y_test,y_pred)) # correlation between actual and predicted value

Mean Squared Error: 27.195965766883205
Root Mean Squared Error: 5.214975145375403
R^2 Score: 0.6733825506400195


## Logistic Regression

Logistic regression is used to describe data and to explain the relationship between one dependent binary variable and one or more independent variables

In [7]:
#Required packages
from sklearn.linear_model import LogisticRegression #Logistic regression package
from sklearn.model_selection import train_test_split

In [8]:
#Importing a dataset for logistic regression
from sklearn.datasets import load_breast_cancer
cancer = load_breast_cancer()
X = cancer["data"]
y = cancer['target']
#Split the data into training and testing datasets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [9]:
#Syntax for creating a Logistic Regression model

# LogisticRegression(penalty='l2', *, dual=False, tol=0.0001, C=1.0, fit_intercept=True, 
# intercept_scaling=1, class_weight=None, random_state=None, solver='lbfgs', max_iter=100, 
# multi_class='auto', verbose=0, warm_start=False, n_jobs=None, l1_ratio=None)

# Link for explanation of terms : https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html

#Simple model
logreg = LogisticRegression(max_iter=3000) 
logreg.fit(X_train,y_train)
y_pred = logreg.predict(X_test)

In [10]:
# Exploring the input & output

# Input: A two-dimensional array which contains all the features of the boston housing dataset
print("Input : ", X_test)

# Output: The ouput array is the prediction
print("Expected output : ", y_test)
print("Predicted output : ", y_pred)

Input :  [[1.900e+01 1.891e+01 1.234e+02 ... 1.218e-01 2.841e-01 6.541e-02]
 [1.427e+01 2.255e+01 9.377e+01 ... 1.362e-01 2.698e-01 8.351e-02]
 [2.013e+01 2.825e+01 1.312e+02 ... 1.628e-01 2.572e-01 6.637e-02]
 ...
 [2.016e+01 1.966e+01 1.311e+02 ... 1.425e-01 3.055e-01 5.933e-02]
 [1.448e+01 2.146e+01 9.425e+01 ... 1.225e-01 3.020e-01 6.846e-02]
 [1.298e+01 1.935e+01 8.452e+01 ... 9.858e-02 3.596e-01 9.166e-02]]
Expected output :  [0 0 0 1 1 0 1 0 0 1 0 1 1 0 1 1 1 1 0 1 0 1 1 0 1 0 1 0 1 1 1 1 1 1 1 0 0
 1 1 1 0 0 0 1 1 0 1 1 1 1 0 0 1 1 0 1 1 1 1 0 0 0 0 1 1 1 0 0 1 1 0 0 1 1
 1 1 1 1 1 0 0 0 1 1 1 1 0 0 1 0 1 1 1 0 1 1 0 0 0 1 1 0 0 0 0 0 1 1 1 1 0
 1 1 1 1 0 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 0 1 1 0 1 1 1 1 1 1 1 0
 1 1 1 1 0 0 1 1 1 0 1 1 1 1 1 0 0 1 1 0 0 0 1]
Predicted output :  [0 1 0 1 1 0 1 1 0 1 0 1 1 0 1 1 1 1 0 1 0 1 1 0 1 0 1 0 1 1 1 1 1 1 1 0 0
 1 1 0 0 0 0 1 1 1 1 1 1 1 0 0 1 1 0 1 1 1 1 1 0 1 0 1 1 1 0 0 1 1 0 0 1 1
 1 1 1 1 1 0 0 0 1 1 1 1 0 0 1 0 1 1 1 0 1 1 0

In [11]:
# Calculating the Accuracy
# Importing necessary packages
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

# Accuracy
print("Test Accuracy Score:", logreg.score(X_test, y_test)) #Predicted correctly/Total values

# Mean Squared Error
print("Mean Squared Error:", mean_squared_error(y_test, y_pred))# tells you how close a regression line is to a set of points

# Root Mean Squared Error
print("Root Mean Squared Error:", mean_squared_error(y_test, y_pred, squared=False)) 

# R2 Score
print("R^2 value", r2_score(y_test,y_pred)) # correlation between actual and predicted value

# Precision
print("Precision:",precision_score(y_test, y_pred)) #Proportion of positive identifications actually correct

# Recall
print("Recall:",recall_score(y_test, y_pred)) # Proportion of actual positives was identified correctly

Test Accuracy Score: 0.9473684210526315
Mean Squared Error: 0.05263157894736842
Root Mean Squared Error: 0.22941573387056177
R^2 value 0.7738095238095238
Precision: 0.9459459459459459
Recall: 0.9722222222222222


## Decision Tree 1 - Iterative Dichotomiser 3

A decision tree is a structure that contains nodes (rectangular boxes) and edges(arrows) and is built from a dataset (with rows and columns). Each node is used to make a decision (decision node) or represent an outcome (leaf node).

In [12]:
#Required packages
from sklearn.tree import DecisionTreeClassifier #Decision Tree Classifier package
from sklearn.model_selection import train_test_split

In [13]:
#Importing a dataset for Decision Tree 1 - Iterative Dichotomiser 3
from sklearn.datasets import load_iris
iris = load_iris()
X = iris.data
y = iris.target
#Split the data into training and testing datasets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)

In [14]:
#Syntax for creating a Decision Tree 1 - Iterative Dichotomiser 3 model

# DecisionTreeClassifier(*, criterion='gini', splitter='best', max_depth=None, min_samples_split=2, 
# min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features=None, random_state=None, 
# max_leaf_nodes=None, min_impurity_decrease=0.0, class_weight=None, ccp_alpha=0.0)

# Link for explanation of terms : https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html

#Simple model
dtc = DecisionTreeClassifier(criterion='entropy',max_depth=3)
dtc.fit(X_train, y_train)
y_pred = dtc.predict(X_test)

In [15]:
# Exploring the input & output

# Input: A two-dimensional array which contains all the features of the boston housing dataset
print("Input : ", X_test)

# Output: The ouput array is the prediction
print("Expected output : ", y_test)
print("Predicted output : ", y_pred)

Input :  [[5.3 3.7 1.5 0.2]
 [5.4 3.4 1.7 0.2]
 [5.  3.4 1.6 0.4]
 [5.  2.3 3.3 1. ]
 [6.7 3.3 5.7 2.1]
 [4.7 3.2 1.6 0.2]
 [5.1 2.5 3.  1.1]
 [5.8 2.7 5.1 1.9]
 [5.1 3.5 1.4 0.2]
 [6.7 3.1 5.6 2.4]
 [6.6 3.  4.4 1.4]
 [5.1 3.4 1.5 0.2]
 [5.4 3.  4.5 1.5]
 [5.  3.5 1.3 0.3]
 [5.4 3.9 1.3 0.4]
 [4.6 3.1 1.5 0.2]
 [5.8 2.8 5.1 2.4]
 [4.9 3.6 1.4 0.1]
 [5.5 2.4 3.7 1. ]
 [7.7 2.8 6.7 2. ]
 [4.8 3.4 1.6 0.2]
 [4.9 3.1 1.5 0.1]
 [4.9 2.4 3.3 1. ]
 [6.2 2.2 4.5 1.5]
 [6.4 2.8 5.6 2.2]
 [6.9 3.2 5.7 2.3]
 [5.6 2.5 3.9 1.1]
 [4.7 3.2 1.3 0.2]
 [7.  3.2 4.7 1.4]
 [7.2 3.6 6.1 2.5]
 [6.4 2.9 4.3 1.3]
 [4.8 3.  1.4 0.3]
 [7.6 3.  6.6 2.1]
 [5.  3.2 1.2 0.2]
 [7.9 3.8 6.4 2. ]
 [5.  2.  3.5 1. ]
 [6.9 3.1 5.1 2.3]
 [5.2 3.5 1.5 0.2]
 [6.7 3.1 4.4 1.4]
 [5.  3.5 1.6 0.6]
 [6.3 2.5 4.9 1.5]
 [5.2 2.7 3.9 1.4]
 [5.5 2.3 4.  1.3]
 [6.5 3.  5.5 1.8]
 [6.8 3.2 5.9 2.3]]
Expected output :  [0 0 0 1 2 0 1 2 0 2 1 0 1 0 0 0 2 0 1 2 0 0 1 1 2 2 1 0 1 2 1 0 2 0 2 1 2
 0 1 0 1 1 1 2 2]
Predicted output :  [0 

In [16]:
# Calculating the Accuracy
# Importing necessary packages
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

# Accuracy
print("Test Accuracy Score:", dtc.score(X_test, y_test)) #Predicted correctly/Total values

# Mean Squared Error
print("Mean Squared Error:", mean_squared_error(y_test, y_pred))# tells you how close a regression line is to a set of points

# Root Mean Squared Error
print("Root Mean Squared Error:", mean_squared_error(y_test, y_pred, squared=False)) 

# R2 Score
print("R^2 value", r2_score(y_test,y_pred)) # correlation between actual and predicted value

# Precision
print("Precision:",precision_score(y_test, y_pred, average='weighted')) #Proportion of positive identifications actually correct

# Recall
print("Recall:",recall_score(y_test, y_pred, average='weighted')) # Proportion of actual positives was identified correctly

Test Accuracy Score: 1.0
Mean Squared Error: 0.0
Root Mean Squared Error: 0.0
R^2 value 1.0
Precision: 1.0
Recall: 1.0


## Decision Tree - CART (Classification and Regression Tree Algorithm)

A classification algorithm for building a decision tree based on Gini's impurity index as splitting criterion

In [17]:
#Required packages
from sklearn.tree import DecisionTreeClassifier #Decision Tree Classifier package
from sklearn.model_selection import train_test_split

In [18]:
#Importing a dataset for Decision Tree 2 - CART
from sklearn.datasets import load_iris
iris = load_iris()
X = iris.data
y = iris.target
#Split the data into training and testing datasets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)

In [19]:
#Syntax for creating a Decision Tree 1 - Iterative Dichotomiser 3 model

# DecisionTreeClassifier(*, criterion='gini', splitter='best', max_depth=None, min_samples_split=2, 
# min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features=None, random_state=None, 
# max_leaf_nodes=None, min_impurity_decrease=0.0, class_weight=None, ccp_alpha=0.0)

# Link for explanation of terms : https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html

#Simple model
dtc_gini = DecisionTreeClassifier(criterion='gini',max_depth=3)
dtc_gini.fit(X_train, y_train)
y_pred = dtc_gini.predict(X_test)

In [20]:
# Exploring the input & output

# Input: A two-dimensional array which contains all the features of the boston housing dataset
print("Input : ", X_test)

# Output: The ouput array is the prediction
print("Expected output : ", y_test)
print("Predicted output : ", y_pred)

Input :  [[5.8 2.7 3.9 1.2]
 [5.4 3.  4.5 1.5]
 [5.5 4.2 1.4 0.2]
 [5.4 3.9 1.3 0.4]
 [6.7 3.  5.  1.7]
 [4.7 3.2 1.6 0.2]
 [6.2 2.9 4.3 1.3]
 [7.7 2.6 6.9 2.3]
 [5.8 2.7 4.1 1. ]
 [6.1 2.6 5.6 1.4]
 [5.5 2.5 4.  1.3]
 [7.1 3.  5.9 2.1]
 [6.1 2.9 4.7 1.4]
 [6.8 3.  5.5 2.1]
 [5.6 2.7 4.2 1.3]
 [6.4 3.1 5.5 1.8]
 [5.  2.  3.5 1. ]
 [7.4 2.8 6.1 1.9]
 [5.2 3.4 1.4 0.2]
 [6.3 2.5 5.  1.9]
 [5.7 2.8 4.5 1.3]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [5.5 2.4 3.8 1.1]
 [6.7 2.5 5.8 1.8]
 [6.7 3.1 4.4 1.4]
 [4.9 3.  1.4 0.2]
 [4.4 3.  1.3 0.2]
 [5.1 3.8 1.6 0.2]
 [6.3 2.9 5.6 1.8]
 [7.2 3.  5.8 1.6]
 [5.6 3.  4.1 1.3]
 [6.5 3.  5.2 2. ]
 [7.7 3.  6.1 2.3]
 [5.8 2.8 5.1 2.4]
 [5.  2.3 3.3 1. ]
 [6.9 3.1 5.1 2.3]
 [5.7 3.  4.2 1.2]
 [5.7 3.8 1.7 0.3]
 [5.7 2.9 4.2 1.3]
 [6.5 3.  5.5 1.8]
 [6.3 2.5 4.9 1.5]
 [6.7 3.3 5.7 2.1]
 [6.1 2.8 4.  1.3]]
Expected output :  [1 1 0 0 1 0 1 2 1 2 1 2 1 2 1 2 1 2 0 2 1 0 0 0 1 2 1 0 0 0 2 2 1 2 2 2 1
 2 1 0 1 2 1 2 1]
Predicted output :  [1 

In [21]:
# Calculating the Accuracy
# Importing necessary packages
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

# Accuracy
print("Test Accuracy Score:", dtc.score(X_test, y_test)) #Predicted correctly/Total values

# Mean Squared Error
print("Mean Squared Error:", mean_squared_error(y_test, y_pred))# tells you how close a regression line is to a set of points

# Root Mean Squared Error
print("Root Mean Squared Error:", mean_squared_error(y_test, y_pred, squared=False)) 

# R2 Score
print("R^2 value", r2_score(y_test,y_pred)) # correlation between actual and predicted value

# Precision
print("Precision:",precision_score(y_test, y_pred, average='weighted')) #Proportion of positive identifications actually correct

# Recall
print("Recall:",recall_score(y_test, y_pred, average='weighted')) # Proportion of actual positives was identified correctly

Test Accuracy Score: 0.9777777777777777
Mean Squared Error: 0.022222222222222223
Root Mean Squared Error: 0.14907119849998599
R^2 value 0.9621848739495799
Precision: 0.9790849673202615
Recall: 0.9777777777777777


## Naive Bayes Algorithm

### Type 1 - Gaussian Naive Bayes Algorithm 

Gaussian Naive Bayes Algorithm is used when the features have continuous values, when the features are following a gaussian distribution i.e, normal distribution

In [22]:
#Required packages
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

In [23]:
#Importing a dataset for Naive Bayes Algorithm
from sklearn.datasets import load_iris
iris = load_iris()
X = iris.data
y = iris.target
#Split the data into training and testing datasets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)

In [24]:
#Syntax for creating a Naive Bayes Algorithm

#GaussianNB(*, priors=None, var_smoothing=1e-09)

#Link for explanation of the model: https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.GaussianNB.html

#Simple model
gnb = GaussianNB()
gnb.fit(X_train, y_train)
y_pred = gnb.predict(X_test)

In [25]:
# Exploring the input & output

# Input: A two-dimensional array which contains all the features of the boston housing dataset
print("Input : ", X_test)

# Output: The ouput array is the prediction
print("Expected output : ", y_test)
print("Predicted output : ", y_pred)

Input :  [[6.3 2.5 4.9 1.5]
 [7.7 2.8 6.7 2. ]
 [4.9 2.4 3.3 1. ]
 [5.6 3.  4.5 1.5]
 [6.1 2.8 4.  1.3]
 [6.5 3.2 5.1 2. ]
 [5.  3.  1.6 0.2]
 [6.6 2.9 4.6 1.3]
 [6.8 2.8 4.8 1.4]
 [5.  3.5 1.6 0.6]
 [7.7 3.  6.1 2.3]
 [7.6 3.  6.6 2.1]
 [5.  2.3 3.3 1. ]
 [6.3 3.3 6.  2.5]
 [7.7 3.8 6.7 2.2]
 [6.9 3.1 5.4 2.1]
 [4.8 3.  1.4 0.1]
 [6.2 3.4 5.4 2.3]
 [6.  2.7 5.1 1.6]
 [6.  2.2 5.  1.5]
 [5.5 2.4 3.7 1. ]
 [4.4 3.2 1.3 0.2]
 [6.1 2.8 4.7 1.2]
 [5.8 2.7 4.1 1. ]
 [5.8 4.  1.2 0.2]
 [4.4 3.  1.3 0.2]
 [6.2 2.9 4.3 1.3]
 [7.2 3.2 6.  1.8]
 [6.  2.9 4.5 1.5]
 [5.1 3.8 1.9 0.4]
 [5.1 3.7 1.5 0.4]
 [5.4 3.7 1.5 0.2]
 [6.5 2.8 4.6 1.5]
 [6.3 2.3 4.4 1.3]
 [5.6 2.7 4.2 1.3]
 [7.2 3.6 6.1 2.5]
 [5.7 2.8 4.5 1.3]
 [6.3 2.9 5.6 1.8]
 [5.  3.3 1.4 0.2]
 [5.8 2.7 5.1 1.9]
 [5.9 3.  5.1 1.8]
 [4.8 3.4 1.9 0.2]
 [5.  3.4 1.5 0.2]
 [5.4 3.4 1.5 0.4]
 [5.4 3.9 1.7 0.4]]
Expected output :  [1 2 1 1 1 2 0 1 1 0 2 2 1 2 2 2 0 2 1 2 1 0 1 1 0 0 1 2 1 0 0 0 1 1 1 2 1
 2 0 2 2 0 0 0 0]
Predicted output :  [1 

In [26]:
# Calculating the Accuracy
# Importing necessary packages
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

# Accuracy
print("Test Accuracy Score:", gnb.score(X_test, y_test)) #Predicted correctly/Total values

# Mean Squared Error
print("Mean Squared Error:", mean_squared_error(y_test, y_pred))# tells you how close a regression line is to a set of points

# Root Mean Squared Error
print("Root Mean Squared Error:", mean_squared_error(y_test, y_pred, squared=False)) 

# R2 Score
print("R^2 value", r2_score(y_test,y_pred)) # correlation between actual and predicted value

# Precision
print("Precision:",precision_score(y_test, y_pred, average='weighted')) #Proportion of positive identifications actually correct

# Recall
print("Recall:",recall_score(y_test, y_pred, average='weighted')) # Proportion of actual positives was identified correctly

Test Accuracy Score: 0.9555555555555556
Mean Squared Error: 0.044444444444444446
Root Mean Squared Error: 0.21081851067789195
R^2 value 0.9285714285714286
Precision: 0.9555555555555556
Recall: 0.9555555555555556


## KMeans Clustering algorithm

The K-means clustering algorithm computes centroids and repeats until the optimal centroid is found

In [ ]:
#Required packages
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt 
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split

In [ ]:
# Upload your data as a csv file and load it as a data frame 
df = pd.read_csv('penguins.csv').dropna()
df.head()

In [ ]:
#Using the elbow method to find out the optimal number of KMeans clusters
X = np.array(df.loc[:,['bill_length_mm','bill_depth_mm']]).reshape(-1, 2)

# Determine optimal cluster number with elbow method
wcss = []

for i in range(1, 11):
    model = KMeans(n_clusters = i,init = 'k-means++',max_iter = 300,n_init = 10,random_state = 0)
    model.fit(X)                              
    wcss.append(model.inertia_)
    
# Show Elbow plot
plt.plot(range(1, 11), wcss)
plt.title('Elbow Method')                               # Set plot title
plt.xlabel('Number of clusters')                        # Set x axis name
plt.ylabel('Within Cluster Sum of Squares (WCSS)')      # Set y axis name
plt.show()

In [ ]:
#Syntax for creating a KMeans Clustering Algorithm

#KMeans(n_clusters=8, *, init='k-means++', n_init=10, max_iter=300, tol=0.0001, verbose=0, random_state=None, 
#copy_x=True, algorithm='lloyd')

#n_clusters - amount of clusters
#max_iter - maximum number of iteration
#n_init - How often algorithm will run with different centroid
#random_state - Choose random state for reproducibility

#Link for explanation of the model: https://scikit-learn.org/stable/modules/generated/sklearn.cluster.KMeans.html

#Simple model
kmeans = KMeans(n_clusters = 3,max_iter = 300,n_init = 10,random_state = 0)    
y_pred = kmeans.fit_predict(X)

In [ ]:
# Exploring the input & output

# Input: A two-dimensional array which contains all the features of the boston housing dataset
print("Input : ", X)

# Output: The ouput array is the prediction
print("Class of output : ", y_pred)

In [ ]:
#Evaluate the KMeans model using silhouette samples
from sklearn.metrics import silhouette_samples
for i, k in enumerate([2, 3, 4]):
    fig, ax1 = plt.subplots(1)
    fig.set_size_inches(18, 7)
    
    # Run the Kmeans algorithm
    km = KMeans(n_clusters=k)
    labels = km.fit_predict(X_train)
    centroids = km.cluster_centers_

    # Get silhouette samples
    silhouette_vals = silhouette_samples(X_train, labels)

    # Silhouette plot
    y_ticks = []
    y_lower, y_upper = 0, 0
    for i, cluster in enumerate(np.unique(labels)):
        cluster_silhouette_vals = silhouette_vals[labels == cluster]
        cluster_silhouette_vals.sort()
        y_upper += len(cluster_silhouette_vals)
        ax1.barh(range(y_lower, y_upper), cluster_silhouette_vals, edgecolor='none', height=1)
        ax1.text(-0.03, (y_lower + y_upper) / 2, str(i + 1))
        y_lower += len(cluster_silhouette_vals)

    # Get the average silhouette score and plot it
    avg_score = np.mean(silhouette_vals)
    ax1.axvline(avg_score, linestyle='--', linewidth=2, color='green')
    ax1.set_yticks([])
    ax1.set_xlim([-0.1, 1])
    ax1.set_xlabel('Silhouette coefficient values')
    ax1.set_ylabel('Cluster labels')
    ax1.set_title('Silhouette plot for the various clusters', y=1.02);
    plt.suptitle(f'Silhouette analysis using k = {k}',fontsize=16, fontweight='semibold', y=1.05);

## KNN Classifier (K Nearest Neighbours)

KNN works by finding the distances between a query and all the examples in the data, selecting the specified number examples (K) closest to the query, then votes for the most frequent label (in the case of classification) or averages the labels (in the case of regression)

In [ ]:
#Required packages
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

In [ ]:
#Importing a dataset for Naive Bayes Algorithm
from sklearn.datasets import load_wine
wine = load_wine()
X = wine.data
y = wine.target
#Split the data into training and testing datasets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [ ]:
#Syntax for creating a KNN Classifier model

#class sklearn.neighbors.KNeighborsClassifier(n_neighbors=5, *, weights='uniform', algorithm='auto', leaf_size=30,
#p=2, metric='minkowski', metric_params=None, n_jobs=None)

#Link for explanation : https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html

#Simple model
for i in range(1,21):
    knn = KNeighborsClassifier(n_neighbors=i)
    knn.fit(X_train,y_train)
    y_pred = knn.predict(X_test)
    from sklearn.metrics import accuracy_score
    print(i)
    print("accuracy= ",accuracy_score(y_test,y_pred))

In [ ]:
knn = KNeighborsClassifier(n_neighbors=13)
knn.fit(X_train,y_train)
y_pred = knn.predict(X_test)
from sklearn.metrics import accuracy_score
print("accuracy= ",accuracy_score(y_test,y_pred))

In [ ]:
# Exploring the input & output

# Input: A two-dimensional array which contains all the features of the wine dataset
print("Input : ", X_test)

# Output: The ouput array is the prediction
print("Expected output : ", y_test)
print("Predicted output : ", y_pred)

In [ ]:
# Calculating the Accuracy
# Importing necessary packages
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

# Accuracy
print("Test Accuracy Score:", knn.score(X_test, y_test)) #Predicted correctly/Total values

# Mean Squared Error
print("Mean Squared Error:", mean_squared_error(y_test, y_pred))# tells you how close a regression line is to a set of points

# Root Mean Squared Error
print("Root Mean Squared Error:", mean_squared_error(y_test, y_pred, squared=False)) 

# R2 Score
print("R^2 value:", r2_score(y_test,y_pred)) # correlation between actual and predicted value

# Precision
print("Precision:",precision_score(y_test, y_pred, average='weighted')) #Proportion of positive identifications actually correct

# Recall
print("Recall:",recall_score(y_test, y_pred, average='weighted')) # Proportion of actual positives was identified correctly

## Support Vector Classifier (SVC)

Support vector machines (SVMs) are powerful yet flexible supervised machine learning methods used for classification, regression, and, outliers' detection.

SVC fits the data provided, returning a "best fit" hyperplane that divides, or categorizes the data. 

In [ ]:
#Required packages
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split

In [ ]:
#Importing a dataset for Support Vector Classifier Algorithm
from sklearn.datasets import load_breast_cancer
breast_cancer = load_breast_cancer()
X = breast_cancer.data
y = breast_cancer.target
#Split the data into training and testing datasets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [ ]:
# Syntax for creating a Support Vector Classifier model:


# SVC(*, C=1.0, kernel='rbf', degree=3, gamma='scale', coef0=0.0, shrinking=True, probability=False, tol=0.001, 
# cache_size=200, class_weight=None, verbose=False, max_iter=- 1, decision_function_shape='ovr', break_ties=False,
# random_state=None)

# Link for explanation of terms : https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html

# A simple model:
svc = SVC()
svc.fit(X_train, y_train)
y_pred = svc.predict(X_test)

In [ ]:
# Exploring the input & output

# Input: A two-dimensional array which contains all the features of the breast cancer dataset
print("Input : ", X_test)

# Output: The ouput array is the prediction
print("Expected output : ", y_test)
print("Predicted output : ", y_pred)

In [ ]:
# Calculating the Accuracy
# Importing necessary packages
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

# Accuracy
print("Test Accuracy Score:", svc.score(X_test, y_test)) #Predicted correctly/Total values

# Mean Squared Error
print("Mean Squared Error:", mean_squared_error(y_test, y_pred))# tells you how close a regression line is to a set of points

# Root Mean Squared Error
print("Root Mean Squared Error:", mean_squared_error(y_test, y_pred, squared=False)) 

# R2 Score
print("R^2 value:", r2_score(y_test,y_pred)) # correlation between actual and predicted value

# Precision
print("Precision:",precision_score(y_test, y_pred, average='weighted')) #Proportion of positive identifications actually correct

# Recall
print("Recall:",recall_score(y_test, y_pred, average='weighted')) # Proportion of actual positives was identified correctly

## Principal Component Analysis (PCA)

Principal Component Analysis (PCA) is an unsupervised machine learning algorithm which can be used as a linear dimensionality reduction technique that can be utilized for extracting information from a high-dimensional space by projecting it into a lower-dimensional sub-space.

PCA can't be used for prediction itself but can be used to reduce the dimensions in the training data to fit in for some algorithms such as KMeans etc.

In [ ]:
#Required packages
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split

In [ ]:
#Importing a dataset for Principal Component Analysis
from sklearn.datasets import load_iris
iris = load_iris()
X = iris.data
y = iris.target
#Split the data into training and testing datasets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)

In [ ]:
X

In [ ]:
pca = PCA(n_components=2)
pca.fit_transform(X)

## Random Forest Classifier

A classifier that contains a number of decision trees on various subsets of the given dataset and takes the average to improve the predictive accuracy of that dataset

In [ ]:
# Required packages
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [ ]:
#Importing a dataset for Random Forest Classifier Algorithm
from sklearn.datasets import load_wine
wine = load_wine()
X = wine.data
y = wine.target
#Split the data into training and testing datasets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [ ]:
# Syntax for creating a Random Forest Classifier model:


# RandomForestClassifier(n_estimators=100, *, criterion='gini', max_depth=None, min_samples_split=2, 
# min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features='sqrt', max_leaf_nodes=None, 
# min_impurity_decrease=0.0, bootstrap=True, oob_score=False, n_jobs=None, random_state=None, verbose=0, 
# warm_start=False, class_weight=None, ccp_alpha=0.0, max_samples=None)

# Link for explanation of terms : https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html

# A simple model:
rfm = RandomForestClassifier()
rfm.fit(X_train, y_train)
y_pred = rfm.predict(X_test)

In [ ]:
# Exploring the input & output

# Input: A two-dimensional array which contains all the features of the breast cancer dataset
print("Input : ", X_test)

# Output: The ouput array is the prediction
print("Expected output : ", y_test)
print("Predicted output : ", y_pred)

In [ ]:
# Calculating the Accuracy
# Importing necessary packages
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

# Accuracy
print("Test Accuracy Score:", rfm.score(X_test, y_test)) #Predicted correctly/Total values

# Mean Squared Error
print("Mean Squared Error:", mean_squared_error(y_test, y_pred))# tells you how close a regression line is to a set of points

# Root Mean Squared Error
print("Root Mean Squared Error:", mean_squared_error(y_test, y_pred, squared=False)) 

# R2 Score
print("R^2 value:", r2_score(y_test,y_pred)) # correlation between actual and predicted value

# Precision
print("Precision:",precision_score(y_test, y_pred, average='weighted')) #Proportion of positive identifications actually correct

# Recall
print("Recall:",recall_score(y_test, y_pred, average='weighted')) # Proportion of actual positives was identified correctly

## Gradient Boosting Classifier Algorithm

Gradient Boosting Classifier Algorithm gives a prediction model in the form of an ensemble of weak prediction models, which are typically decision trees

In [ ]:
#Required packages
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import train_test_split

In [ ]:
#Importing a dataset for Random Forest Classifier Algorithm
from sklearn.datasets import load_breast_cancer
breast_cancer = load_breast_cancer()
X = breast_cancer.data
y = breast_cancer.target
#Split the data into training and testing datasets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [ ]:
 # Syntax for creating a Gradient Boosting Classifier model:


# GradientBoostingClassifier(*, loss='log_loss', learning_rate=0.1, n_estimators=100, subsample=1.0, 
# criterion='friedman_mse', min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_depth=3,
# min_impurity_decrease=0.0, init=None, random_state=None, max_features=None, verbose=0, max_leaf_nodes=None,
# warm_start=False, validation_fraction=0.1, n_iter_no_change=None, tol=0.0001, ccp_alpha=0.0)

# Link for explanation of terms : https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.GradientBoostingClassifier.html

# A simple model:
gbc = GradientBoostingClassifier()
gbc.fit(X_train, y_train)
y_pred = gbc.predict(X_test)

In [ ]:
# Exploring the input & output

# Input: A two-dimensional array which contains all the features of the diabetes dataset
print("Input : ", X_test)

# Output: The ouput array is the prediction
print("Expected output : ", y_test)
print("Predicted output : ", y_pred)

In [ ]:
# Calculating the Accuracy
# Importing necessary packages
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

# Accuracy
print("Test Accuracy Score:", gbc.score(X_test, y_test)) #Predicted correctly/Total values

# Mean Squared Error
print("Mean Squared Error:", mean_squared_error(y_test, y_pred))# tells you how close a regression line is to a set of points

# Root Mean Squared Error
print("Root Mean Squared Error:", mean_squared_error(y_test, y_pred, squared=False)) 

# R2 Score
print("R^2 value:", r2_score(y_test,y_pred)) # correlation between actual and predicted value

# Precision
print("Precision:",precision_score(y_test, y_pred, average='weighted')) #Proportion of positive identifications actually correct

# Recall
print("Recall:",recall_score(y_test, y_pred, average='weighted')) # Proportion of actual positives was identified correctly

## Ada Boost Classifier Algorithm

An AdaBoost classifier is a meta-estimator that begins by fitting a classifier on the original dataset and then fits additional copies of the classifier on the same dataset but where the weights of incorrectly classified instances are adjusted such that subsequent classifiers focus more on difficult cases.

In [ ]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.datasets import make_classification

In [ ]:
X, y = make_classification(n_samples=1000, n_features=4,n_informative=2, n_redundant=0)    

In [ ]:
 # Syntax for creating a Ada Boost Classifier model:


# AdaBoostClassifier(base_estimator=None, *, n_estimators=50, learning_rate=1.0, algorithm='SAMME.R', 
# random_state=None)

# Link for explanation of terms : https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.AdaBoostClassifier.html

# A simple model:
abc = AdaBoostClassifier(n_estimators=100)
abc.fit(X, y)
y_pred = abc.predict(X)

In [ ]:
# Exploring the input & output

# Input: A two-dimensional array which contains all the features of the diabetes dataset
print("Input : ", X)

# Output: The ouput array is the prediction
print("Expected output : ", y)
print("Predicted output : ", y_pred)

In [ ]:
# Calculating the Accuracy
# Importing necessary packages
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

# Accuracy
print("Test Accuracy Score:", abc.score(X, y)) #Predicted correctly/Total values

# Mean Squared Error
print("Mean Squared Error:", mean_squared_error(y, y_pred))# tells you how close a regression line is to a set of points

# Root Mean Squared Error
print("Root Mean Squared Error:", mean_squared_error(y, y_pred, squared=False)) 

# R2 Score
print("R^2 value:", r2_score(y,y_pred)) # correlation between actual and predicted value

# Precision
print("Precision:",precision_score(y, y_pred, average='weighted')) #Proportion of positive identifications actually correct

# Recall
print("Recall:",recall_score(y, y_pred, average='weighted')) # Proportion of actual positives was identified correctly